# SQL Interview Questions  - Quiz


## Introduction

This quiz contains questions on topics you can expect to see in an interview pertaining to SQL and Relational Databases. Some of them are multiple choice, while some are short answer. For these short answer questions, double click on the Jupyter Notebook and type your answer below the line. 

## Question 1

What are the 4 main datatypes in SQLite3? Can we use other common types from other kinds of SQL?

Type your answer below this line:
_______________________________________________________________________________________________________________________________

TEXT, INTEGER, REAL, BLOB
Yes, for example you can use int or float and it will map to integer or real.



## Question 2

Explain the relationship between **Primary Keys** and **Foreign Keys**.

Type your answer below this line:
_______________________________________________________________________________________________________________________________

Primary keys are unique identifiers in a specific table and a foreign key resides in said table but is a primary in another table.



## Question 3

Explain the different types of relationships entities can have in a SQL database. 

Type your answer below this line:
_______________________________________________________________________________________________________________________________

one-to-one: student to student id
one-to-many: teacher to student aka one teach to many students
many-to-many: student to subject matter aka a student can take many subjects and a subject has many students enrolled


## Question 4

Explain the various types of JOINs possible with SQL. 

Type your answer below this line:
_______________________________________________________________________________________________________________________________

Inner - includes only items that fall in both tables
Left - includes inner and left table
Right - includes inner and right table
Outer - excludes inner


## Question 5

Explain the relationship between Aggregate functions and GROUP BY statements.

Type your answer below this line:
_______________________________________________________________________________________________________________________________

When you group your data by a certain variable you will need to choose an aggregation function for another variable. For instance a table of students and the classes they are in, if you want to see the number of classes each student is taking you can group by student and COUNT() the classes. The COUNT() is the aggregation function.


## Question 6

What role do Associative Entities play (JOIN Tables) in many-to-many JOINs?


Type your answer below this line:
_______________________________________________________________________________________________________________________________

In order to join tables you must have a one-to-one or one-to-many relationship. You cannot have a many-to-many relationship. You therefore build associative entity tables between many-to-many tables to bridge this gap. For instance, student to subject create a table that has a student id and a course id (there are same courses on multiple days mutiple times therefore one student can only be in one of these).


## Summary

In this lesson, we practiced answering open-ended interview questions for SQL and Relational Databases.